port: 7880
bind_address: ""
room:
  empty_timeout: 300
logging:
  level: info
keys:
  devkey: secret

# port: 7880

# rtc:
#   use_external_ip: true
#   turn_servers:
#     - host: openrelay.metered.ca
#       port: 80
#       username: openrelayproject
#       credential: openrelayproject
#       protocol: udp
#     - host: openrelay.metered.ca  
#       port: 443
#       username: openrelayproject
#       credential: openrelayproject
#       protocol: tcp

# keys:
#   devkey: secret

# logging:
#   level: info