version: "2"
authtoken: 30ohbe9KHcQb6aM0ZoPNcl063bi_7HQvbjPiHi1XbmbDF7hgV

tunnels:
  # FastAPI Server (Frontend + API)
  server:
    proto: http
    addr: 8000

  # LiveKit Server (WebSocket)
  livekit:
    proto: http
    addr: 7880